#!/usr/bin/zsh

sudo apt install -y cron

# install ngrok
curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

stow -d "$HOME/.dotfiles" -t "$HOME" --restow server

touch $HOME/.dotfiles/server-deps
