#!/usr/bin/zsh

usage() {
  echo "usage: $0 [-h] host user address" >&${1:-1}
  echo >&${1:-1}
  echo 'positional arguments:' >&${1:-1}
  echo '  host' >&${1:-1}
  echo '  user' >&${1:-1}
  echo '  address' >&${1:-1}
  echo >&${1:-1}
  echo 'optional argument:' >&${1:-1}
  echo '  -h, --help            show this help message and exit' >&${1:-1}
}

has_argument() {
  [[ ("$1" == *=* && -n ${1#*=}) || ( ! -z "$2" && "$2" != -*) ]];
}

extract_argument() {
  echo "${2:-${1#*=}}"
}

error() {
  echo "$1" >&2
}

port=''
while [ $# -gt 0 ]; do
  case $1 in
    -h | --help)
      usage
      exit
    ;;
    -*)
      error "invalid option: $1"
      exit 1
    ;;
    *)
      break
    ;;
  esac
  shift
done

if [ $# != 3 ]; then
  error 'invalid positional arguments'
  usage 2
  exit 1
fi

host=$1
user=$2
address=$3

ssh_config="$HOME/.ssh/config.d/$host"

# strip protocol
address=${address#(*://)}

# strip port
url=${address%(:*)}

# strip url
port=${address##(*:)}

echo "Host $host" >$ssh_config
echo "  User $user" >>$ssh_config
echo "  HostName $url" >>$ssh_config
if [[ -n "$port" ]]; then 
  echo "  Port $port" >>$ssh_config
fi
echo '  ForwardAgent yes' >>$ssh_config
